const ADDBASKET = 'ADDBASKET'
const BOOKLISTLOAD = 'BOOCKLISTLOAD'
const SELECTCATEGORY = 'SELECTCATEGORY'
const ONCHANGEPRICEFROM = 'ONCHANGEPRICEFROM'
const ONCHANGEPRICEBEFORE = 'ONCHANGEPRICEBEFORE'
const SEARCH = 'SEARCH'
const PAGINATION = 'PAGINATION'
const RESETPAGENUMBER = 'RESETPAGENUMBER'
const SEARCHINPUT = 'SEARCHINPUT'
const SERACHBUTTONCLICK = 'SERACHBUTTONCLICK'
const SORTEDPRICELOWER = 'SORTEDPRICELOWER'
const SORTEDPRICEHIGH = 'SORTEDPRICEHIGH'
const SORTEDNEWBOOK = 'SORTEDNEWBOOK'
const SORTEDPOPULARBOOK = 'SORTEDPOPULARBOOK'
const RESETSORTED = 'RESETSORTED'
const CATEGORYLOAD = 'CATEGORYLOAD'
const REGISTRATION = 'REGISTRATION'
const REGISTRATION_RESPONSE = 'REGISTRATION_RESPONSE'
const ADDTOBASKETLIST = 'ADDTOBASKETLIST'
const REMOVEBASKETITEM = 'REMOVEBASKETITEM'
const ISLOGIN = "ISLOGIN"
const LOGOUT = 'LOGOUT'


export {
    ADDBASKET,
    BOOKLISTLOAD,
    SELECTCATEGORY,
    ONCHANGEPRICEFROM,
    ONCHANGEPRICEBEFORE,
    SEARCH,
    PAGINATION,
    RESETPAGENUMBER,
    SEARCHINPUT,
    SERACHBUTTONCLICK,
    SORTEDPRICELOWER,
    SORTEDPRICEHIGH,
    SORTEDNEWBOOK,
    SORTEDPOPULARBOOK,
    RESETSORTED,
    CATEGORYLOAD,
    REGISTRATION,
    REGISTRATION_RESPONSE,
    ADDTOBASKETLIST,
    REMOVEBASKETITEM,
    ISLOGIN,
    LOGOUT
}
