const ADDBASKET = 'ADDBASKET'
const BOOKLISTLOAD = 'BOOCKLISTLOAD'
const FILTERBOOCKS = 'FILTERBOOCKS'
const ONCHANGEPRICEFROM = 'ONCHANGEPRICEFROM'
const ONCHANGEPRICEBEFORE = 'ONCHANGEPRICEBEFORE'
const SEARCH = 'SEARCH'
const PAGINATION = 'PAGINATION'
const RESETPAGENUMBER = 'RESETPAGENUMBER'

export {
    ADDBASKET,
    BOOKLISTLOAD,
    FILTERBOOCKS,
    ONCHANGEPRICEFROM,
    ONCHANGEPRICEBEFORE,
    SEARCH,
    PAGINATION,
    RESETPAGENUMBER
}
