const ADDBASKET = 'ADDBASKET'
const BOOKLISTLOAD = 'BOOCKLISTLOAD'
const FILTERBOOCKS = 'FILTERBOOCKS'
const ONCHANGEPRICEFROM = 'ONCHANGEPRICEFROM'
const ONCHANGEPRICEBEFORE = 'ONCHANGEPRICEBEFORE'
const SEARCH = 'SEARCH'

export {
    ADDBASKET,
    BOOKLISTLOAD,
    FILTERBOOCKS,
    ONCHANGEPRICEFROM,
    ONCHANGEPRICEBEFORE,
    SEARCH
}
